source 'http://rubygems.org'

gem 'rails', '3.0.10'
gem 'em-http-request'
gem 'em-synchrony'
gem 'girl_friday'
gem 'mongoid', '~> 2.1'
gem 'mongoid_rails_migrations', '0.0.13'
gem 'bson_ext', '~> 1.3'
gem 'thin'
gem 'inherited_resources'
gem 'formtastic', '~> 1.2.3'
gem 'tabs_on_rails'
gem 'jquery-rails'
gem 'kaminari', '0.12.4'
gem 'dalli'
